### ISSUE TITLE
Reducing multiple png files to a zip archive only used the first image

### ISSUE THREAD

**Issue by ipfaze** [mothsART/machin#10]
### What happened?

When trying to reduce multiple png file to a zip archive, the command below produces a zip containing the first image multiple time.
```bash
ls ~/Downloads/*.png | ~/Projects/Rust/machin/target/debug/machreduce -o result.zip
```

### What did you expect to happen?

We expect to generate a zip archive containing all the png images not only the first one.

### Machin version

I'm using the current version available on the master branch, the last commit hash is [2c33926edda9f7471331f90aa9b4d499bea4aaf6](https://github.com/mothsART/machin/commit/2c33926edda9f7471331f90aa9b4d499bea4aaf6)

### Steps to reproduce it

1. Pull the master branch
2. Build project using `cargo build`
3. Download some png image
4. Try to reduce it using `ls *.png | machreduce -o result.zip`

The result of those steps should produce an incorrect zip archive.

##### Example

List of png files to reduce : 

1. `bitcoin.png`
2. `butterfly.png`
3. `coin.png`
4. `pineapple.png`

Expected a zip archive containing all the png file correctly but get :

1. `bitcoin.png`       -->  displayed `bitcoin.png`
2. `butterfly.png`    -->  displayed `bitcoin.png`
3. `coin.png`           -->  displayed `bitcoin.png`
4. `pineapple.png` -->  displayed `bitcoin.png`

**Comment by mothsART** [comment]
Correction here : https://github.com/mothsART/machin/pull/11

Thanks for involvement.
