### ISSUE TITLE
Converting a yaml file to a json rearrange its contents in alphabetical order

### ISSUE THREAD

**Issue by ipfaze** [mothsART/machin#14]
## What happened?
When converting a yaml file to an json file, it's rearrange its contents in alphabetical order.

I'm using this commands :
`ls *.yaml | machmap -e json`

## What did you expect to happen?
We expect to generate a json file which is content should have the same order as the yaml file.

## Machin version
I'm using the last version available

## Example
[Here](https://github.com/mothsART/machin/files/9508813/Example.files.zip) you can find an ZIP archive containing the yaml file used to test this feature and the json result.

**Comment by mothsART** [comment]
fix here : https://github.com/mothsART/machin/pull/15

Thanks
