### ISSUE TITLE
Converting a png file to an avif file never finish

### ISSUE THREAD

**Issue by ipfaze** [mothsART/machin#6]
### What happened?

When trying to convert a png file to an avif file, the command below never finishes and write `Rgba8` in the terminal.

ls ~/Downloads/pineapple.png | ~/Projects/Rust/machin/target/debug/machmap -e pdf

### What did you expect to happen?

We expect to generate an avif file containing the image.

### Machin version

I'm using the current version available on the master branch, the last commit hash is [2c33926edda9f7471331f90aa9b4d499bea4aaf6](https://github.com/mothsART/machin/commit/2c33926edda9f7471331f90aa9b4d499bea4aaf6)

### Steps to reproduce it

1. Pull the master branch
2. Build project using cargo build
3. Download a png image
4. Try to convert it using `ls image_file.png | machmap -e avif`

The result of those steps should write `Rgba8` in the terminal and the process never finish.

**Comment by mothsART** [comment]
same issue as https://github.com/mothsART/machin/issues/7 (edited)
