### ISSUE TITLE
Converting an image (png, jpg) to an avif file never finish

### ISSUE THREAD

**Issue by ipfaze** [mothsART/machin#7]
### What happened?

When trying to convert a jpg file to an avif file, the command below never finishes.

ls ~/Downloads/sparrow.jpg | ~/Projects/Rust/machin/target/debug/machmap -e pdf

### What did you expect to happen?

We expect to generate an avif file containing the image.

### Machin version

I'm using the current version available on the master branch, the last commit hash is [2c33926edda9f7471331f90aa9b4d499bea4aaf6](https://github.com/mothsART/machin/commit/2c33926edda9f7471331f90aa9b4d499bea4aaf6)

### Steps to reproduce it

1. Pull the master branch
2. Build project using cargo build
3. Download a jpg image
4. Try to convert it using `ls image_file.jpg | machmap -e avif`

The process never finish.

**Comment by mothsART** [comment]
I think it's extremly slowly : https://github.com/image-rs/image/issues/1760

If you want test it, tried it with extremly small picture and with `cargo build --release`
I've commented issue of image-rs lib. I think than their algorithm can be  adapt to be as quick than imagemagick.

But, actually, you right. It's not usable.
I will removed this feature.

**Comment by mothsART** [comment]
Version 0.5.3 published : https://github.com/mothsART/machin/blob/master/CHANGELOG.md#053----2022-08-19
I removed the feature. (I hope temporarily)

**Comment by ipfaze** [comment]
Thank you for your investigation, hope this feature will come back soon !

**Comment by mothsART** [comment]
After a long period of forgetfulness, I finally updated ìmage` dependency and noticed a clear improvement.
performances are not as good as C projects like `Imagemagic`, but it's still acceptable.

PR : https://github.com/mothsART/machin/pull/22
