### ISSUE TITLE
Converting an svg file to a png or a jpg file lost the svg filename

### ISSUE THREAD

**Issue by ipfaze** [mothsART/machin#8]
### What happened?

When trying to convert an svg file to a jpg or png file, the command below generates the correct file, but it's named `output` instead of the svg filename.

ls ~/Downloads/motorcycle.svg | ~/Projects/Rust/machin/target/debug/machmap -e pdf

### What did you expect to happen?

We expect to generate a jpg or png file with the same filename as the svg.

### Machin version

I'm using the current version available on the master branch, the last commit hash is [2c33926edda9f7471331f90aa9b4d499bea4aaf6](https://github.com/mothsART/machin/commit/2c33926edda9f7471331f90aa9b4d499bea4aaf6)

### Steps to reproduce it

1. Pull the master branch
2. Build project using cargo build
3. Download an svg image
4. Try to convert it using `ls image_file.svg | machmap -e png` or `ls image_file.svg | machmap -e jpg`

The result of those steps should generate the converted file named `output` instead of `image_file`

**Comment by mothsART** [comment]
Fixed on https://github.com/mothsART/machin/pull/12
Thanks for reporting
